export const NasaTypes = {
  FILTER_APODS: 'FILTER_APODS',
  FILTER_APODS_SUCCESS: 'FILTER_APODS_SUCCESS',
  ACTIVITY_LOADING: 'ACTIVITY_LOADING',
  FETCH_APODS: 'FETCH_APODS',
  FETCH_APODS_SUCCESS: 'FETCH_APODS_SUCCESS',
  SAVE_APOD: 'SAVE_APOD',
  DELETE_APOD: 'DELETE_APOD',
  FETCH_ACTIVITY_LOADING: 'FETCH_ACTIVITY_LOADING',
  SAVE_ACTIVITY_LOADING: 'SAVE_ACTIVITY_LOADING'
}